"""Windows Event ID library for Leblebi"""

# Comprehensive Windows Security Event ID descriptions
# Based on Microsoft documentation and security best practices

WINDOWS_EVENT_DESCRIPTIONS = {
    # Authentication Events
    '4624': 'Successful Logon',
    '4625': 'Failed Logon Attempt',
    '4648': 'Logon with Explicit Credentials',
    '4672': 'Special Privileges Assigned',
    '4768': 'Kerberos Authentication Ticket Requested',
    '4769': 'Kerberos Service Ticket Requested',
    '4770': 'Kerberos Service Ticket Renewed',
    '4771': 'Kerberos Pre-authentication Failed',
    '4772': 'Kerberos Authentication Ticket Request Failed',
    '4774': 'Account Mapped for Logon',
    '4775': 'Account Cannot Be Mapped for Logon',
    '4776': 'Domain Controller Validated Account Credentials',
    '4777': 'Domain Controller Failed to Validate Account Credentials',
    
    # Account Management
    '4720': 'User Account Created',
    '4722': 'User Account Enabled',
    '4723': 'Attempt to Change Password',
    '4724': 'Attempt to Reset Password',
    '4725': 'User Account Disabled',
    '4726': 'User Account Deleted',
    '4727': 'Security-Enabled Global Group Created',
    '4728': 'Member Added to Security-Enabled Global Group',
    '4729': 'Member Removed from Security-Enabled Global Group',
    '4730': 'Security-Enabled Global Group Deleted',
    '4731': 'Security-Enabled Local Group Created',
    '4732': 'Member Added to Security-Enabled Local Group',
    '4733': 'Member Removed from Security-Enabled Local Group',
    '4734': 'Security-Enabled Local Group Deleted',
    '4735': 'Security-Enabled Local Group Changed',
    '4737': 'Security-Enabled Global Group Changed',
    '4738': 'User Account Changed',
    '4739': 'Domain Policy Changed',
    '4740': 'User Account Locked Out',
    '4741': 'Computer Account Created',
    '4742': 'Computer Account Changed',
    '4743': 'Computer Account Deleted',
    
    # Logon/Logoff
    '4634': 'Account Logged Off',
    '4647': 'User Initiated Logoff',
    '4675': 'SIDs Were Filtered',
    
    # Object Access
    '4656': 'Handle to Object Requested',
    '4657': 'Registry Value Modified',
    '4658': 'Handle to Object Closed',
    '4659': 'Handle to Object Deleted',
    '4660': 'Object Deleted',
    '4661': 'Handle to Object Requested',
    '4662': 'Operation Performed on Object',
    '4663': 'Attempt to Access Object',
    '4670': 'Permissions on Object Changed',
    
    # Policy Change
    '4704': 'User Right Assigned',
    '4705': 'User Right Removed',
    '4706': 'New Trust Created for Domain',
    '4707': 'Trust Removed for Domain',
    '4713': 'Kerberos Policy Changed',
    '4714': 'Encrypted Data Recovery Policy Changed',
    '4715': 'Audit Policy Changed',
    '4716': 'Trusted Domain Information Modified',
    '4717': 'System Security Access Granted',
    '4718': 'System Security Access Removed',
    '4719': 'System Audit Policy Changed',
    '4739': 'Domain Policy Changed',
    '4864': 'Namespace Collision Detected',
    '4865': 'Trusted Forest Information Entry Added',
    '4866': 'Trusted Forest Information Entry Removed',
    '4867': 'Trusted Forest Information Entry Modified',
    
    # Privilege Use
    '4672': 'Special Privileges Assigned to New Logon',
    '4673': 'Privileged Service Called',
    '4674': 'Operation Attempted on Privileged Object',
    
    # Detailed Tracking
    '4688': 'New Process Created',
    '4689': 'Process Exited',
    '4690': 'Attempt to Duplicate Handle to Object',
    '4691': 'Indirect Access to Object Requested',
    '4692': 'Backup of Data Protection Master Key Attempted',
    '4693': 'Recovery of Data Protection Master Key Attempted',
    '4694': 'Protect Auditable Protected Data Attempted',
    '4695': 'Unprotect Auditable Protected Data Attempted',
    '4696': 'Primary Token Assigned to Process',
    '4697': 'Service Installed in System',
    '4698': 'Scheduled Task Created',
    '4699': 'Scheduled Task Deleted',
    '4700': 'Scheduled Task Enabled',
    '4701': 'Scheduled Task Disabled',
    '4702': 'Scheduled Task Updated',
    
    # System Events
    '4608': 'Windows Started',
    '4609': 'Windows Shutting Down',
    '4610': 'Authentication Package Loaded',
    '4611': 'Trusted Logon Process Registered',
    '4612': 'Internal Resources Allocated for Queued Audit Messages',
    '4614': 'Security Package Loaded',
    '4615': 'Invalid Use of LPC Port',
    '4616': 'System Time Changed',
    '4618': 'Monitored Security Event Pattern Occurred',
    '4621': 'Administrator Recovered System from CrashGuard',
    '4622': 'Security Package Loaded by Local Security Authority',
    '4625': 'Account Failed to Log On',
    '4626': 'Account Name Mapped',
    '4627': 'Group Membership Enumerated',
    '4634': 'Account Logged Off',
    '4647': 'User Initiated Logoff',
    '4648': 'Logon with Explicit Credentials',
    '4649': 'Replay Attack Detected',
    '4650': 'IPsec Main Mode Established',
    '4651': 'IPsec Main Mode Negotiation Failed',
    '4652': 'IPsec Quick Mode Established',
    '4653': 'IPsec Quick Mode Negotiation Failed',
    '4654': 'IPsec Extended Mode Negotiation Failed',
    '4655': 'IPsec Main Mode Security Association Established',
    '4656': 'Handle to Object Requested',
    '4657': 'Registry Value Modified',
    '4658': 'Handle to Object Closed',
    '4659': 'Handle to Object Deleted',
    '4660': 'Object Deleted',
    '4661': 'Handle to Object Requested',
    '4662': 'Operation Performed on Object',
    '4663': 'Attempt to Access Object',
    '4664': 'Attempt to Create Hard Link',
    '4665': 'Attempt to Create Application Client Context',
    '4666': 'Application Attempted Operation',
    '4667': 'Application Client Context Deleted',
    '4668': 'Application Initialized',
    '4670': 'Permissions on Object Changed',
    '4671': 'Application Attempted to Access Blocked Through URL',
    '4672': 'Special Privileges Assigned to New Logon',
    '4673': 'Privileged Service Called',
    '4674': 'Operation Attempted on Privileged Object',
    '4675': 'SIDs Were Filtered',
    '4688': 'New Process Created',
    '4689': 'Process Exited',
    '4690': 'Attempt to Duplicate Handle to Object',
    '4691': 'Indirect Access to Object Requested',
    '4692': 'Backup of Data Protection Master Key Attempted',
    '4693': 'Recovery of Data Protection Master Key Attempted',
    '4694': 'Protect Auditable Protected Data Attempted',
    '4695': 'Unprotect Auditable Protected Data Attempted',
    '4696': 'Primary Token Assigned to Process',
    '4697': 'Service Installed in System',
    '4698': 'Scheduled Task Created',
    '4699': 'Scheduled Task Deleted',
    '4700': 'Scheduled Task Enabled',
    '4701': 'Scheduled Task Disabled',
    '4702': 'Scheduled Task Updated',
    '4703': 'Token Right Adjusted',
    '4704': 'User Right Assigned',
    '4705': 'User Right Removed',
    '4706': 'New Trust Created for Domain',
    '4707': 'Trust Removed for Domain',
    '4709': 'IPsec Security Association Deleted',
    '4710': 'IPsec Security Association Established',
    '4711': 'IPsec Security Association Established',
    '4712': 'IPsec Security Association Established',
    '4713': 'Kerberos Policy Changed',
    '4714': 'Encrypted Data Recovery Policy Changed',
    '4715': 'Audit Policy Changed',
    '4716': 'Trusted Domain Information Modified',
    '4717': 'System Security Access Granted',
    '4718': 'System Security Access Removed',
    '4719': 'System Audit Policy Changed',
    '4720': 'User Account Created',
    '4722': 'User Account Enabled',
    '4723': 'Attempt to Change Password',
    '4724': 'Attempt to Reset Password',
    '4725': 'User Account Disabled',
    '4726': 'User Account Deleted',
    '4727': 'Security-Enabled Global Group Created',
    '4728': 'Member Added to Security-Enabled Global Group',
    '4729': 'Member Removed from Security-Enabled Global Group',
    '4730': 'Security-Enabled Global Group Deleted',
    '4731': 'Security-Enabled Local Group Created',
    '4732': 'Member Added to Security-Enabled Local Group',
    '4733': 'Member Removed from Security-Enabled Local Group',
    '4734': 'Security-Enabled Local Group Deleted',
    '4735': 'Security-Enabled Local Group Changed',
    '4737': 'Security-Enabled Global Group Changed',
    '4738': 'User Account Changed',
    '4739': 'Domain Policy Changed',
    '4740': 'User Account Locked Out',
    '4741': 'Computer Account Created',
    '4742': 'Computer Account Changed',
    '4743': 'Computer Account Deleted',
    '4768': 'Kerberos Authentication Ticket Requested',
    '4769': 'Kerberos Service Ticket Requested',
    '4770': 'Kerberos Service Ticket Renewed',
    '4771': 'Kerberos Pre-authentication Failed',
    '4772': 'Kerberos Authentication Ticket Request Failed',
    '4773': 'Kerberos Service Ticket Request Failed',
    '4774': 'Account Mapped for Logon',
    '4775': 'Account Cannot Be Mapped for Logon',
    '4776': 'Domain Controller Validated Account Credentials',
    '4777': 'Domain Controller Failed to Validate Account Credentials',
    '4778': 'Session Reconnected to Window Station',
    '4779': 'Session Disconnected from Window Station',
    '4780': 'ACL Set on Accounts Which Members of Administrators Group',
    '4781': 'Name of Account Changed',
    '4782': 'Password Hash Accessed',
    '4783': 'Basic Application Group Created',
    '4784': 'Basic Application Group Changed',
    '4785': 'Member Added to Basic Application Group',
    '4786': 'Member Removed from Basic Application Group',
    '4787': 'Non-Member Added to Basic Application Group',
    '4788': 'Non-Member Removed from Basic Application Group',
    '4789': 'Basic Application Group Deleted',
    '4790': 'LDAP Query Group Created',
    '4791': 'Basic Application Group Changed',
    '4792': 'LDAP Query Group Changed',
    '4793': 'LDAP Query Group Deleted',
    '4794': 'Security-Enabled Local Group Membership Enumerated',
    '4795': 'Security-Enabled Global Group Membership Enumerated',
    '4796': 'Security-Enabled Universal Group Membership Enumerated',
    '4797': 'Security-Enabled Local Group Membership Enumerated',
    '4798': 'Security-Enabled Global Group Membership Enumerated',
    '4799': 'Security-Enabled Universal Group Membership Enumerated',
    '4800': 'Workstation Locked',
    '4801': 'Workstation Unlocked',
    '4802': 'Screen Saver Invoked',
    '4803': 'Screen Saver Dismissed',
    '4816': 'RPC Detected an Integrity Violation While Decrypting an Incoming Message',
    '4817': 'Auditing Settings on Object Changed',
    '4818': 'Proposed Central Access Policy Does Not Grant the Same Access Permissions as Current Central Access Policy',
    '4819': 'Central Access Policies on Machine Changed',
    '4820': 'Kerberos Ticket Granting Ticket (TGT) Was Denied Because the Device Does Not Meet the Access Control Restrictions',
    '4821': 'Kerberos Service Ticket Was Denied Because the Device Does Not Meet the Access Control Restrictions',
    '4822': 'NTLM Authentication Failed Because the Account Was a Member of the Protected User Group',
    '4823': 'NTLM Authentication Failed Because the Account Was a Member of the Protected User Group',
    '4824': 'Kerberos Pre-authentication Succeeded',
    '4825': 'User Denied Access to Remote Desktop',
    '4826': 'Boot Configuration Data Loaded',
    '4827': 'Boot Configuration Data Failed to Load',
    '4828': 'Boot Configuration Data Failed to Load',
    '4829': 'Boot Configuration Data Failed to Load',
    '4830': 'SID History Was Removed from Account',
    '4864': 'Namespace Collision Detected',
    '4865': 'Trusted Forest Information Entry Added',
    '4866': 'Trusted Forest Information Entry Removed',
    '4867': 'Trusted Forest Information Entry Modified',
    '4868': 'Certificate Manager Denied a Pending Certificate Request',
    '4869': 'Certificate Services Received a Resubmitted Certificate Request',
    '4870': 'Certificate Services Revoked a Certificate',
    '4871': 'Certificate Services Received a Request to Publish the Certificate Revocation List (CRL)',
    '4872': 'Certificate Services Published the Certificate Revocation List (CRL)',
    '4873': 'Certificate Request Extension Added to Certificate Request',
    '4874': 'Certificate Request Extension Modified in Certificate Request',
    '4875': 'Certificate Request Extension Removed from Certificate Request',
    
    # Log Clearing
    '1102': 'Audit Log Cleared',
    '1104': 'Security Log Now Full',
    '1105': 'Event Log Service Shut Down',
    '1108': 'Event Logging Service Encountered an Error',
    
    # Other Important Events
    '5140': 'Network Share Object Was Accessed',
    '5142': 'Network Share Object Was Added',
    '5143': 'Network Share Object Was Modified',
    '5144': 'Network Share Object Was Deleted',
    '5145': 'Network Share Object Access Check',
    '5154': 'Windows Firewall Rule Added',
    '5155': 'Windows Firewall Rule Modified',
    '5156': 'Windows Firewall Rule Deleted',
    '5157': 'Windows Firewall Rule Changed',
    '5158': 'Windows Firewall Rule List Changed',
    '5159': 'IPsec Filter Blocked a Packet',
    '5168': 'SPN Check for SMB Session',
    '5169': 'SMB Session Established',
    '5170': 'SMB Session Disconnected',
}


def get_event_description(event_id: str) -> str:
    """Get description for Windows Event ID"""
    return WINDOWS_EVENT_DESCRIPTIONS.get(str(event_id), 'Unknown Event')

